apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'bootstrap'
  namespace: argocd
  annotations:
    documentation: "https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: 'base'
    repoURL: 'https://github.com/nkzk/workshop.git'
    targetRevision: HEAD
  project: 'workshop'